rent/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from rent import views
from rent.views import (IndexView,
                        AboutUsView,
                        ContactUsView,
                        RentCarView,
                        CarPhotoView,
                        SuccessView,
                        RegisterView)

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutUsView.as_view(), name='about_us'),
    path('contact/', ContactUsView.as_view(), name='contact_us'),
    path('rent/<int:car_id>/', RentCarView.as_view(), name='rent_car'),
    path('car_photo/<int:car_id>/', CarPhotoView.as_view(), name='car_detail'),
    path('success/', SuccessView.as_view(), name='success'),


    # Authentication
    path('accounts/login/', views.UserLoginView.as_view(), name='login'),
    path('accounts/register/', RegisterView.as_view(), name='register'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html'
    ), name='password_change_done'),
    path('accounts/password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),
    path('accounts/password-reset-confirm/<uidb64>/<token>/',
         views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ), name='password_reset_complete'),
]

app_name = "rent"

rent_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("rent.urls", namespace="rent")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxi_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taxi.urls", namespace="taxi")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/accounts/password_change.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Creative Tim {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-left">
              <h4 class="font-weight-bolder">Change Password</h4>
              <p class="mb-0">Enter your new password here.</p>
            </div>
            <div class="card-body">
              <form method="post" action="#" role="form">
                {% csrf_token %}

                {% for field in form %}
                <div class="mb-3">
                  {{ field }}
                </div>
                <span class="text-danger"> {{ field.errors }} </span>
                {% endfor %}
                <div class="text-center">
                  <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Change</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/illustrations/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">"Attention is the new currency"</h4>
            <p class="text-white">The more effortless the writing looks, the more effort the writer actually put into the process.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block footer %}

{% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/accounts/password_change_done.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Creative Tim {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-left">
              <h4 class="font-weight-bolder">Password Changed</h4>
            </div>
            <div class="card-body">
              Your password has been changed successfully.
            </div>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/illustrations/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">"Attention is the new currency"</h4>
            <p class="text-white">The more effortless the writing looks, the more effort the writer actually put into the process.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block footer %}

{% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/accounts/password_reset.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Creative Tim {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-left">
              <h4 class="font-weight-bolder">Reset Password</h4>
              <p class="mb-0">Enter your registered email address</p>
            </div>
            <div class="card-body">
              <form method="post" action="#" role="form">
                {% csrf_token %}

                {% for field in form %}
                <div class="mb-3">
                  {{ field }}
                </div>
                <span class="text-danger"> {{ field.errors }} </span>
                {% endfor %}
                <div class="text-center">
                  <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Reset</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/illustrations/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">"Attention is the new currency"</h4>
            <p class="text-white">The more effortless the writing looks, the more effort the writer actually put into the process.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block footer %}

{% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/accounts/password_reset_complete.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Creative Tim {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-left">
              <h4 class="font-weight-bolder">Password Changed</h4>
            </div>
            <div class="card-body">
              Your password has been changed successfully. Login again.
                  <a class="text-primary" href="{% url 'login' %}">Login</a>
            </div>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/illustrations/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">"Attention is the new currency"</h4>
            <p class="text-white">The more effortless the writing looks, the more effort the writer actually put into the process.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block footer %}

{% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/accounts/password_reset_confirm.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Creative Tim {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-left">
              <h4 class="font-weight-bolder">Reset Password</h4>
              <p class="mb-0">Enter your new password here.</p>
            </div>
            <div class="card-body">
              <form method="post" action="#" role="form">
                {% csrf_token %}

                {% for field in form %}
                <div class="mb-3">
                  {{ field }}
                </div>
                <span class="text-danger"> {{ field.errors }} </span>
                {% endfor %}
                <div class="text-center">
                  <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Reset</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/illustrations/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">"Attention is the new currency"</h4>
            <p class="text-white">The more effortless the writing looks, the more effort the writer actually put into the process.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block footer %}

{% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/accounts/password_reset_done.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Creative Tim {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-left">
              <h4 class="font-weight-bolder">Email Sent</h4>
            </div>
            <div class="card-body">
              An email has been sent to your email address. Please click the link and reset your password.
            </div>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/illustrations/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">"Attention is the new currency"</h4>
            <p class="text-white">The more effortless the writing looks, the more effort the writer actually put into the process.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block footer %}

{% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/accounts/sign-in.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Creative Tim {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-left">
              <h4 class="font-weight-bolder">Sign In</h4>
              <p class="mb-0">Enter your email and password to sign in</p>
            </div>
            <div class="card-body">
              <form method="post" action="#" role="form">
                {% csrf_token %}

                {% if form.non_field_errors %}
                  {% for error in form.non_field_errors %}
                    <span class="text-danger"> {{ error }} </span>
                  {% endfor %}
                {% endif %}

                {% for field in form %}
                  <div class="mb-3">
                    {{ field }}
                  </div>
                  <span class="text-danger"> {{ field.errors }} </span>
                {% endfor %}
                <div class="form-check form-switch">
                  <input class="form-check-input" type="checkbox" id="rememberMe">
                  <label class="form-check-label" for="rememberMe">Remember me</label>
                </div>
                <a href="{% url 'rent:password_reset' %}" class="text-primary text-gradient font-weight-bold">Forgot Password?</a>
                <div class="text-center">
                  <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Sign in</button>
                </div>
              </form>
            </div>
            <div class="card-footer text-center pt-0 px-lg-2 px-1">
              <p class="mb-4 text-sm mx-auto">
                Don't have an account?
                <a href="{% url 'rent:register' %}" class="text-primary text-gradient font-weight-bold">Sign up</a>
              </p>
            </div>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/illustrations/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">"Attention is the new currency"</h4>
            <p class="text-white">The more effortless the writing looks, the more effort the writer actually put into the process.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block footer %}

{% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/accounts/sign-up.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Creative Tim {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

{% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

<section>
  <div class="page-header min-vh-100">
    <div class="container">
      <div class="row">
        <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
          <div class="card card-plain">
            <div class="card-header pb-0 text-left">
              <h4 class="font-weight-bolder">Sign Up</h4>
              <p class="mb-0">Enter your valid credentials to register</p>
            </div>
            <div class="card-body">
              <form method="post" action="#" role="form">
                {% csrf_token %}

                {% for field in form %}
                <div class="mb-3">
                  {{ field }}
                </div>
                <span class="text-danger"> {{ field.errors }} </span>
                {% endfor %}
                <div class="text-center">
                  <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Sign Up</button>
                </div>
              </form>
            </div>
            <div class="card-footer text-center pt-0 px-lg-2 px-1">
              <p class="mb-4 text-sm mx-auto">
                Already have an account?
                <a href="{% url 'login' %}" class="text-primary text-gradient font-weight-bold">Sign In</a>
              </p>
            </div>
          </div>
        </div>
        <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines" class="position-absolute opacity-4 start-0">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2" src="{% static 'img/illustrations/chat.png' %}">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">"Attention is the new currency"</h4>
            <p class="text-white">The more effortless the writing looks, the more effort the writer actually put into the process.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

{% block footer %}

{% include 'includes/footer_signin.html' %}

{% endblock footer %}