rent/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from rent import views
from rent.views import (IndexView,
                        AboutUsView,
                        ContactUsView,
                        RentCarView,
                        CarPhotoView,
                        SuccessView,
                        RegisterView)

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutUsView.as_view(), name='about_us'),
    path('contact/', ContactUsView.as_view(), name='contact_us'),
    path('rent/<int:car_id>/', RentCarView.as_view(), name='rent_car'),
    path('car_photo/<int:car_id>/', CarPhotoView.as_view(), name='car_detail'),
    path('success/', SuccessView.as_view(), name='success'),


    # Authentication
    path('accounts/login/', views.UserLoginView.as_view(), name='login'),
    path('accounts/register/', RegisterView.as_view(), name='register'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html'
    ), name='password_change_done'),
    path('accounts/password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),
    path('accounts/password-reset-confirm/<uidb64>/<token>/',
         views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ), name='password_reset_complete'),
]

app_name = "rent"

rent_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("rent.urls", namespace="rent")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxi_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taxi.urls", namespace="taxi")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/pages/about-us.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Best rent car {% endblock title %}

{% block body %} class="about-us" {% endblock body %}


{% block content %}

  <!-- -------- START HEADER 7 w/ text and video ------- -->
  <header class="bg-gradient-dark">
    <div class="page-header min-vh-75" style="background-image: url('{% static 'img/office-dark.jpg' %}');">
      <span class="mask bg-gradient-info opacity-8"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">Learn more about Rent cars' story</h1>
            <p class="lead mb-4 text-white opacity-8">Rent cars is the largest online car rental platform in Latin
              America and one of the global leaders in the industry. Through the website or app, we provide mobility
              solutions in more than 160 countries and compare prices from over 300 rental companies, bringing together
              the best options in one place.
              Founded in 2009, Rent cars aims to connect people to the best car options worldwide and provide the best
              service so that each customer can have an incredible and satisfying experience from the beginning to the
              end of their journey.</p>
            <button type="submit" class="btn bg-white text-dark">Create Account</button>
            <h6 class="text-white mb-2 mt-5">Find us on</h6>
            <div class="d-flex justify-content-center">
              <a href="javascript:;"><i class="fab fa-facebook text-lg text-white me-4"></i></a>
              <a href="javascript:;"><i class="fab fa-instagram text-lg text-white me-4"></i></a>
              <a href="javascript:;"><i class="fab fa-twitter text-lg text-white me-4"></i></a>
              <a href="javascript:;"><i class="fab fa-google-plus text-lg text-white"></i></a>
            </div>
          </div>
        </div>
      </div>
  </header>
{% endblock content %}

templates/pages/contact-us.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Material Kit 2 by Creative Tim {% endblock title %}

{% block body %} class="contact-us" {% endblock body %}

{% block content %}

<!-- -------- START HEADER 8 w/ card over right bg image ------- -->
<header>
  <div class="page-header min-vh-85">
    <div>
      <img
          class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0"
          src="{% static 'img/curved-images/curved8.jpg' %}" alt="image">
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-7 d-flex justify-content-center flex-column">
          <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
            <div class="text-center">
              <h3 class="text-gradient text-primary">Contact us</h3>
              <p class="mb-0">
                For further questions, including partnership opportunities, please email hello@creative-tim.com
                or contact using our contact form.
              </p>
            </div>
            <form id="contact-form" method="post" autocomplete="off">
              <div class="card-body pb-2">
                <div class="row">
                  <div class="col-md-6">
                    <label>Full Name</label>
                    <div class="input-group mb-4">
                      <input class="form-control" placeholder="Full Name" aria-label="Full Name" type="text">
                    </div>
                  </div>
                  <div class="col-md-6 ps-md-2">
                    <label>Email</label>
                    <div class="input-group">
                      <input type="email" class="form-control" placeholder="hello@creative-tim.com">
                    </div>
                  </div>
                </div>
                <div class="form-group mb-0 mt-md-0 mt-4">
                  <label>How can we help you?</label>
                  <textarea name="message" class="form-control" id="message" rows="6"
                            placeholder="Describe your problem in at least 250 characters"></textarea>
                </div>
                <div class="row">
                  <div class="col-md-12 text-center">
                    <button type="submit" class="btn bg-gradient-primary mt-3 mb-0">Send Message</button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

{% endblock content %}

templates/pages/index.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Best rent car company {% endblock title %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}

<header class="header-2">
  <div class="page-header min-vh-75 relative"
       style="background-image: url('{% static "img/curved-images/curved.jpg" %}')">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 text-center mx-auto">
          <h1 class="text-white pt-3 mt-n5">Rent car</h1>
          <p class="lead text-white mt-3">The best rent car in world <br/> Join over 1.4 million people. </p>
        </div>
      </div>
    </div>

    <div class="position-absolute w-100 z-index-1 bottom-0">
      <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
           viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
          <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
        </defs>
        <g class="moving-waves">
          <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"/>
          <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"/>
          <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"/>
          <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"/>
          <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"/>
          <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95"/>
        </g>
      </svg>
    </div>
  </div>
</header>


<section class="pt-3 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
        <div class="row">
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary"><span id="state1" countTo="{{ num_cars }}">0</span>+</h1>
              <h5 class="mt-3">Different car models</h5>
              <p class="text-sm">Here you can find a car that exactly suits you</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary"><span id="state2" countTo="{{ num_drivers }}">0</span>+</h1>
              <h5 class="mt-3">Countries</h5>
              <p class="text-sm">We cover more and more countries around the world</p>
            </div>
            <hr class="vertical dark">
          </div>
          <div class="col-md-4">
            <div class="p-3 text-center">
              <h1 class="text-gradient text-primary" id="state3" countTo="{{ num_visits }}">0</h1>
              <h5 class="mt-3">Views today</h5>
              <p class="text-sm">Hurry up, choose your car and hit the road</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="album py-5 bg-body-tertiary">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for car in page_obj %}
        {% if car.image %}
        <div class="col">
          <div class="card shadow-sm anime">
            <a href="{% url 'rent:car_detail' car.id %}">
            <img src="{{ car.image.url }}" class="card-img-top" alt="{{ car.model }}">
            </a>
            <div class="card-body">
              <p class="card-text">{{ car.model }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'rent:rent_car' car.id %}" class="btn btn-sm btn-outline-secondary">Rent now</a>
                </div>
                <small class="text-body-secondary">{{ car.price_per_day }} USD/per day</small>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
</div>

<nav aria-label="Page navigation">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1" aria-label="First">
          <span aria-hidden="true">&laquo;&laquo;</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <li class="page-item active" aria-current="page"><span class="page-link">{{ num }}</span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
          <span aria-hidden="true">&raquo;&raquo;</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>


      {% endblock content %}

      {% block javascripts %}

      <script type="text/javascript">

          if (document.getElementById('state1')) {
              const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
              if (!countUp.error) {
                  countUp.start();
              } else {
                  console.error(countUp.error);
              }
          }
          if (document.getElementById('state2')) {
              const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
              if (!countUp1.error) {
                  countUp1.start();
              } else {
                  console.error(countUp1.error);
              }
          }
          if (document.getElementById('state3')) {
              const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
              if (!countUp2.error) {
                  countUp2.start();
              } else {
                  console.error(countUp2.error);
              }
              ;
          }
      </script>

      {% endblock javascripts %}