rent/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from rent import views
from rent.views import (IndexView,
                        AboutUsView,
                        ContactUsView,
                        RentCarView,
                        CarPhotoView,
                        SuccessView,
                        RegisterView)

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutUsView.as_view(), name='about_us'),
    path('contact/', ContactUsView.as_view(), name='contact_us'),
    path('rent/<int:car_id>/', RentCarView.as_view(), name='rent_car'),
    path('car_photo/<int:car_id>/', CarPhotoView.as_view(), name='car_detail'),
    path('success/', SuccessView.as_view(), name='success'),


    # Authentication
    path('accounts/login/', views.UserLoginView.as_view(), name='login'),
    path('accounts/register/', RegisterView.as_view(), name='register'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html'
    ), name='password_change_done'),
    path('accounts/password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),
    path('accounts/password-reset-confirm/<uidb64>/<token>/',
         views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ), name='password_reset_complete'),
]

app_name = "rent"

rent_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("rent.urls", namespace="rent")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxi/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .views import (
    index,
    about_us,
    contact_us,
)

urlpatterns = [
    path("", index, name="index"),
    path('about-us/', about_us, name='about-us'),
    path('contact-us/', contact_us, name='contact-us'),
    path('rent-car/<int:car_id>/', views.rent_car, name='rent_car'),
    path('success/', views.success, name='success'),
    path('car/<int:car_id>/', views.car_photo, name='car_detail'),

    # Authentication
    path('accounts/login/', views.UserLoginView.as_view(), name='login'),
    path('accounts/register/', views.register, name='register'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html'
    ), name='password_change_done'),
    path('accounts/password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),
    path('accounts/password-reset-confirm/<uidb64>/<token>/',
         views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ), name='password_reset_complete'),
]

app_name = "taxi"

taxi_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taxi.urls", namespace="taxi")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxi/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Manufacturer(models.Model):
    name = models.CharField(max_length=255, unique=True)
    country = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} {self.country}"


class Driver(AbstractUser):
    license_number = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "driver"
        verbose_name_plural = "drivers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("taxi:driver-detail", kwargs={"pk": self.pk})


class Car(models.Model):
    image = models.ImageField(upload_to='cars/', blank=True, null=True)
    price_per_day = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    model = models.CharField(max_length=255)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, related_name="manufacturer")
    drivers = models.ManyToManyField(Driver, related_name="cars")

    def __str__(self):
        return self.model


class CarInsideImage(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='inside_images')
    image_inside = models.ImageField(upload_to='car_inside/')

    def __str__(self):
        return f"Image of {self.car.model}"


class Booking(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name="car")
    start_date = models.DateField()
    end_date = models.DateField()
    name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return f"Booking for {self.car} from {self.start_date} to {self.end_date}"

taxi/forms.py
from django import forms
from django.contrib.auth.forms import (UserCreationForm,
                                       AuthenticationForm,
                                       PasswordResetForm,
                                       SetPasswordForm,
                                       PasswordChangeForm,
                                       UsernameField)
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from taxi.models import Booking


class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Password'}),
    )
    password2 = forms.CharField(
        label=_("Password Confirmation"),
        widget=forms.PasswordInput(
            attrs={'class': 'form-control form-control-lg', 'placeholder': 'Password Confirmation'}),
    )

    class Meta:
        model = User
        fields = ('username', 'email',)

        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Username'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Email'
            })
        }


class UserLoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(attrs={"class": "form-control form-control-lg", "placeholder": "Username"}))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"class": "form-control form-control-lg", "placeholder": "Password"}),
    )


class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control form-control-lg',
        'placeholder': 'Email'
    }))


class UserSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg', 'placeholder': 'New Password'
    }), label="New Password")
    new_password2 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg', 'placeholder': 'Confirm New Password'
    }), label="Confirm New Password")


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg', 'placeholder': 'Old Password'
    }), label="New Password")
    new_password1 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg', 'placeholder': 'New Password'
    }), label="New Password")
    new_password2 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg', 'placeholder': 'Confirm New Password'
    }), label="Confirm New Password")


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['start_date', 'end_date', 'name', 'email']
        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
        }

templates/taxi/car_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete car</h1>
  <p>Are you sure you want to delete the car: {{ car }}?</p>
  <p><i>All car with this manufacturer will be also deleted!</i></p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
    <a href="{% url "taxi:car-list" %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/taxi/car_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Car list <a style="float: right" href="{% url "taxi:car-create" %}">+</a></h1>

  {% if car_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for car in car_list %}
        <tr>
          <td>
            {{ car.id }}
          </td>
          <td>
            {{ car.model }}
          </td>
          <td>
            <a href="{% url "taxi:car-update" pk=car.id %}" class="btn btn-primary">UPDATE</a>
          </td>
          <td>
            <a href="{% url "taxi:car-delete" pk=car.id %}" class="btn btn-danger">DELETE</a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no cars in taxi</p>
  {% endif %}
{% endblock %}

templates/taxi/car_rent.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Rent car {% endblock title %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}

<header class="bg-gradient-light">
  <div class="page-header min-vh-75" style="background-image: url('{% static "img/blog7-2.jpg" %}');">
  <div class="col-5 mx-auto my-auto">

    <h1>Book {{ car }}</h1>
    {% if messages %}
    <div id="message-container">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
    </div>
    {% endif %}
    <form method="post" class="form_text">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Rent</button>
    </form>

  </div>
  <span class="mask bg-gradient-info opacity-2"></span>
  </div>
</header>

{% endblock content %}

{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function() {
    const messageContainer = document.getElementById('message-container');
    if (messageContainer) {
      Swal.fire({
        title: 'Success!',
        text: messageContainer.innerText.trim(),
        icon: 'success',
        timer: 3000,
        timerProgressBar: true,
        didClose: () => {
          window.location.href = '{% url "taxi:index" %}';
        }
      });
    }
  });
</script>
{% endblock javascripts %}

templates/taxi/manufacturer_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete manufacturer</h1>
  <p>Are you sure you want to delete the manufacturer: {{ manufacturer }}?</p>
  <p><i>This manufacturer will be also deleted!</i></p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
    <a href="{% url "taxi:manufacturer-list" %}" class=" btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/taxi/manufacturer_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Manufacturer List <a style="float: right" href="{% url "taxi:manufacturer-create" %}">+</a></h1>

  {% if manufacturer_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Country</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for manufacturer in manufacturer_list %}
        <tr>
          <td>
            {{ manufacturer.id }}
          </td>
          <td>
            {{ manufacturer.name }}
          </td>
          <td>
            {{ manufacturer.country }}
          </td>
          <td>
            <a href="{% url "taxi:manufacturer-update" pk=manufacturer.id %}" class="btn btn-primary">UPDATE</a>
          </td>
          <td>
            <a href="{% url "taxi:manufacturer-delete" pk=manufacturer.id %}" class="btn btn-danger">DELETE</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no manufacturers in the service.</p>
  {% endif %}
{% endblock %}