rent/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from rent import views
from rent.views import (IndexView,
                        AboutUsView,
                        ContactUsView,
                        RentCarView,
                        CarPhotoView,
                        SuccessView,
                        RegisterView)

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutUsView.as_view(), name='about_us'),
    path('contact/', ContactUsView.as_view(), name='contact_us'),
    path('rent/<int:car_id>/', RentCarView.as_view(), name='rent_car'),
    path('car_photo/<int:car_id>/', CarPhotoView.as_view(), name='car_detail'),
    path('success/', SuccessView.as_view(), name='success'),


    # Authentication
    path('accounts/login/', views.UserLoginView.as_view(), name='login'),
    path('accounts/register/', RegisterView.as_view(), name='register'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html'
    ), name='password_change_done'),
    path('accounts/password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),
    path('accounts/password-reset-confirm/<uidb64>/<token>/',
         views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ), name='password_reset_complete'),
]

app_name = "rent"

rent_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("rent.urls", namespace="rent")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxi_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taxi.urls", namespace="taxi")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rent/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Manufacturer(models.Model):
    name = models.CharField(max_length=255, unique=True)
    country = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} {self.country}"


class Driver(AbstractUser):
    license_number = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "driver"
        verbose_name_plural = "drivers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("rent:driver-detail", kwargs={"pk": self.pk})


class Car(models.Model):
    image = models.ImageField(upload_to='cars/', blank=True, null=True)
    price_per_day = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    model = models.CharField(max_length=255)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, related_name="manufacturer")
    drivers = models.ManyToManyField(Driver, related_name="cars")

    def __str__(self):
        return self.model


class CarInsideImage(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='inside_images')
    image_inside = models.ImageField(upload_to='car_inside/')

    def __str__(self):
        return f"Image of {self.car.model}"


class Booking(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name="car")
    start_date = models.DateField()
    end_date = models.DateField()
    name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return f"Booking for {self.car} from {self.start_date} to {self.end_date}"

rent/forms.py
from django import forms
from django.contrib.auth.forms import (UserCreationForm,
                                       AuthenticationForm,
                                       PasswordResetForm,
                                       SetPasswordForm,
                                       PasswordChangeForm,
                                       UsernameField)
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from rent.models import Booking


class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg', 'placeholder': 'Password'}),
    )
    password2 = forms.CharField(
        label=_("Password Confirmation"),
        widget=forms.PasswordInput(
            attrs={'class': 'form-control form-control-lg', 'placeholder': 'Password Confirmation'}),
    )

    class Meta:
        model = User
        fields = ('username', 'email',)

        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Username'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Email'
            })
        }


class UserLoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(attrs={"class": "form-control form-control-lg", "placeholder": "Username"}))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"class": "form-control form-control-lg", "placeholder": "Password"}),
    )


class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control form-control-lg',
        'placeholder': 'Email'
    }))


class UserSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg', 'placeholder': 'New Password'
    }), label="New Password")
    new_password2 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg', 'placeholder': 'Confirm New Password'
    }), label="Confirm New Password")


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg', 'placeholder': 'Old Password'
    }), label="New Password")
    new_password1 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg', 'placeholder': 'New Password'
    }), label="New Password")
    new_password2 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control form-control-lg', 'placeholder': 'Confirm New Password'
    }), label="Confirm New Password")


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['start_date', 'end_date', 'name', 'email']
        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
        }

rent/views.py
from django.contrib import messages
from django.http import HttpRequest, HttpResponse
from django.contrib.auth import logout
from django.contrib.auth.views import (LoginView,
                                        PasswordResetView,
                                        PasswordChangeView,
                                        PasswordResetConfirmView)
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View

from rent.models import Driver, Car, Manufacturer
from rent.forms import (RegistrationForm,
                        UserLoginForm,
                        UserPasswordResetForm,
                        UserSetPasswordForm,
                        UserPasswordChangeForm,
                        BookingForm)


class IndexView(View):

    def get(self, request):
        num_drivers = Driver.objects.count()
        num_cars = Car.objects.count()
        num_manufacturers = Manufacturer.objects.count()
        cars = Car.objects.all().order_by('id')

        paginator = Paginator(cars, 6)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        num_visits = request.session.get("num_visits", 0)
        request.session["num_visits"] = num_visits + 1

        context = {
            "num_drivers": num_drivers,
            "num_cars": num_cars,
            "num_manufacturers": num_manufacturers,
            "num_visits": num_visits + 1,
            "cars": cars,
            "page_obj": page_obj,
        }

        return render(request, "pages/index.html", context=context)


class AboutUsView(View):
    def get(self, request):
        return render(request, 'pages/about-us.html')


class ContactUsView(View):
    def get(self, request):
        return render(request, 'pages/contact-us.html')


class RentCarView(View):
    def get(self, request, car_id):
        car = get_object_or_404(Car, id=car_id)
        form = BookingForm()
        return render(request, 'rent/car_rent.html', {'form': form, 'car': car})

    def post(self, request, car_id):
        car = get_object_or_404(Car, id=car_id)
        form = BookingForm(request.POST)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.car = car
            booking.save()
            messages.success(request, f'Congratulations! You have booked {car.model}')
            return redirect('success')  # Adjust to your success URL

        return render(request, 'rent/car_rent.html', {'form': form, 'car': car})


class CarPhotoView(View):
    def get(self, request, car_id):
        car = get_object_or_404(Car, id=car_id)
        inside_images = car.inside_images.all()
        return render(request, 'rent/car_detail.html', {'car': car, 'inside_images': inside_images})


class SuccessView(View):
    def get(self, request):
        return render(request, 'pages/index.html')


class RegisterView(View):
    def get(self, request):
        form = RegistrationForm()
        context = {'form': form}
        return render(request, 'accounts/sign-up.html', context)

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            print("Account created successfully!")
            return redirect('/accounts/login')
        else:
            print("Registration failed!")

        context = {'form': form}
        return render(request, 'accounts/sign-up.html', context)


class UserLoginView(LoginView):
    template_name = 'accounts/sign-in.html'
    form_class = UserLoginForm


def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect('/accounts/login')


class UserPasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset.html'
    form_class = UserPasswordResetForm


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    form_class = UserSetPasswordForm


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'accounts/password_change.html'
    form_class = UserPasswordChangeForm

templates/rent/car_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete car</h1>
  <p>Are you sure you want to delete the car: {{ car }}?</p>
  <p><i>All car with this manufacturer will be also deleted!</i></p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
    <a href="{% url "rent:car-list" %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/rent/car_detail.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Best rent car {% endblock title %}

{% block body %} class="about-us" {% endblock body %}


{% block content %}

  <!-- -------- START HEADER 7 w/ text and video ------- -->
  <header class="bg-gradient-light">
    <div class="page-header min-vh-75" style="background-image: url('{{ car.image.url }}');">
      <span class="mask bg-gradient-info opacity-2"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
<div class="container mt-4">
    <div id="carCarousel" class="carousel slide">
        <div class="carousel-inner">
            {% for image in inside_images %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                <img src="{{ image.image_inside.url }}" class="d-block w-100" alt="Interior Photo">
            </div>
            {% empty %}
            <p>No images available</p>
            {% endfor %}
        </div>
      </>
        <button class="carousel-control-prev" type="button" data-bs-target="#carCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
</body>
            <div class="d-flex justify-content-center">
              <a href="javascript:;"><i class="fab fa-facebook text-lg text-white me-4"></i></a>
              <a href="javascript:;"><i class="fab fa-instagram text-lg text-white me-4"></i></a>
              <a href="javascript:;"><i class="fab fa-twitter text-lg text-white me-4"></i></a>
              <a href="javascript:;"><i class="fab fa-google-plus text-lg text-white"></i></a>
            </div>
          </div>
        </div>
      </div>
       </header>
{% endblock content %}

templates/rent/car_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} car</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/rent/car_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Car list <a style="float: right" href="{% url "rent:car-create" %}">+</a></h1>

  {% if car_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for car in car_list %}
        <tr>
          <td>
            {{ car.id }}
          </td>
          <td>
            {{ car.model }}
          </td>
          <td>
            <a href="{% url "rent:car-update" pk=car.id %}" class="btn btn-primary">UPDATE</a>
          </td>
          <td>
            <a href="{% url "rent:car-delete" pk=car.id %}" class="btn btn-danger">DELETE</a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no cars in rent</p>
  {% endif %}
{% endblock %}

templates/rent/car_rent.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Rent car {% endblock title %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}

<header class="bg-gradient-light">
  <div class="page-header min-vh-75" style="background-image: url('{% static "img/blog7-2.jpg" %}');">
  <div class="col-5 mx-auto my-auto">

    <h1>Book {{ car }}</h1>
    {% if messages %}
    <div id="message-container">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
    </div>
    {% endif %}
    <form method="post" class="form_text">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Rent</button>
    </form>

  </div>
  <span class="mask bg-gradient-info opacity-2"></span>
  </div>
</header>

{% endblock content %}

{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function() {
    const messageContainer = document.getElementById('message-container');
    if (messageContainer) {
      Swal.fire({
        title: 'Success!',
        text: messageContainer.innerText.trim(),
        icon: 'success',
        timer: 3000,
        timerProgressBar: true,
        didClose: () => {
          window.location.href = '{% url "rent:index" %}';
        }
      });
    }
  });
</script>
{% endblock javascripts %}

templates/rent/contact-us.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Material Kit 2 by Creative Tim {% endblock title %}

{% block body %} class="contact-us" {% endblock body %}

{% block content %}

  <!-- -------- START HEADER 8 w/ card over right bg image ------- -->
  <header>
    <div class="page-header min-vh-85">
      <div>
        <img class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0" src="{% static 'img/curved-images/curved8.jpg' %}" alt="image">
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 d-flex justify-content-center flex-column">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                <h3 class="text-gradient text-primary">Contact us</h3>
                <p class="mb-0">
                  For further questions, including partnership opportunities, please email hello@creative-tim.com
                  or contact using our contact form.
                </p>
              </div>
              <form id="contact-form" method="post" autocomplete="off">
                <div class="card-body pb-2">
                  <div class="row">
                    <div class="col-md-6">
                      <label>Full Name</label>
                      <div class="input-group mb-4">
                        <input class="form-control" placeholder="Full Name" aria-label="Full Name" type="text">
                      </div>
                    </div>
                    <div class="col-md-6 ps-md-2">
                      <label>Email</label>
                      <div class="input-group">
                        <input type="email" class="form-control" placeholder="hello@creative-tim.com">
                      </div>
                    </div>
                  </div>
                  <div class="form-group mb-0 mt-md-0 mt-4">
                    <label>How can we help you?</label>
                    <textarea name="message" class="form-control" id="message" rows="6" placeholder="Describe your problem in at least 250 characters"></textarea>
                  </div>
                  <div class="row">
                    <div class="col-md-12 text-center">
                      <button type="submit" class="btn bg-gradient-primary mt-3 mb-0">Send Message</button>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

  {% endblock content %}

templates/rent/driver_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ driver.username }}
  </h1>

  <p><strong>First name:</strong> {{ driver.first_name }}</p>
  <p><strong>Last name:</strong> {{ driver.last_name }}</p>
  <p><strong>License number:</strong> {{ driver.license_number }}</p>
  <p><strong>Is staff:</strong> {{ driver.is_staff }}</p>

  <div class="ml-3">
    <h4>Cars</h4>

    {% for car in driver.cars.all %}
      <hr>
      <p><strong>Model:</strong> {{ car.model }}</p>
      <p><strong>Manufacturer:</strong> {{ car.manufacturer.name }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ car.id }}</p>

    {% empty %}
      <p>No cars!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/rent/driver_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Driver List
  </h1>

  {% if driver_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>License number</th>
      </tr>
      {% for driver in driver_list %}
        <tr>
          <td>{{ driver.id }}</td>
          <td><a href="{{ driver.get_absolute_url }}">{{ driver.username }} {% if user == driver %} (Me){% endif %}</a>
          </td>
          <td>{{ driver.first_name }}</td>
          <td>{{ driver.last_name }}</td>
          <td>{{ driver.license_number }}</td>
        </tr>
      {% endfor %}

    </table>
  {% else %}
    <p>There are no drivers in the service.</p>
  {% endif %}
{% endblock %}

templates/rent/manufacturer_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete manufacturer</h1>
  <p>Are you sure you want to delete the manufacturer: {{ manufacturer }}?</p>
  <p><i>This manufacturer will be also deleted!</i></p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
    <a href="{% url "rent:manufacturer-list" %}" class=" btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/rent/manufacturer_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <h1>{{ object|yesno:"Update, Create" }} manufacturer</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/rent/manufacturer_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Manufacturer List <a style="float: right" href="{% url "rent:manufacturer-create" %}">+</a></h1>

  {% if manufacturer_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Country</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for manufacturer in manufacturer_list %}
        <tr>
          <td>
            {{ manufacturer.id }}
          </td>
          <td>
            {{ manufacturer.name }}
          </td>
          <td>
            {{ manufacturer.country }}
          </td>
          <td>
            <a href="{% url "rent:manufacturer-update" pk=manufacturer.id %}" class="btn btn-primary">UPDATE</a>
          </td>
          <td>
            <a href="{% url "rent:manufacturer-delete" pk=manufacturer.id %}" class="btn btn-danger">DELETE</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no manufacturers in the service.</p>
  {% endif %}
{% endblock %}